INSERT INTO CONTACT (C_ID, CONTACT_NAME, EMAIL, USER_ID) VALUES (1, 'Anil','anil@gmail.com', 1311);
INSERT INTO CONTACT (C_ID, CONTACT_NAME, EMAIL, USER_ID) VALUES (2, 'Kumar','kumar@gmail.com', 1311);
INSERT INTO CONTACT (C_ID, CONTACT_NAME, EMAIL, USER_ID) VALUES (3, 'Siva','siva@gmail.com', 1312);
INSERT INTO CONTACT (C_ID, CONTACT_NAME, EMAIL, USER_ID) VALUES (4, 'Rakesh','rakesh@gmail.com', 1314);
